package com.alsc.net.db.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.alsc.net.db.bean.BtcWallet;
import com.alsc.net.db.bean.ContactBean;
import com.alsc.net.db.bean.ETHWallet;
import com.alsc.net.db.bean.IdCradBean;
import com.alsc.net.db.bean.UserInfoBean;
import com.alsc.net.retrofit.download.DownInfo;
import com.alsc.net.retrofit.http.cookie.CookieResulte;

import com.alsc.net.db.bean.BtcWalletDao;
import com.alsc.net.db.bean.ContactBeanDao;
import com.alsc.net.db.bean.ETHWalletDao;
import com.alsc.net.db.bean.IdCradBeanDao;
import com.alsc.net.db.bean.UserInfoBeanDao;
import com.alsc.net.db.bean.DownInfoDao;
import com.alsc.net.db.bean.CookieResulteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig btcWalletDaoConfig;
    private final DaoConfig contactBeanDaoConfig;
    private final DaoConfig eTHWalletDaoConfig;
    private final DaoConfig idCradBeanDaoConfig;
    private final DaoConfig userInfoBeanDaoConfig;
    private final DaoConfig downInfoDaoConfig;
    private final DaoConfig cookieResulteDaoConfig;

    private final BtcWalletDao btcWalletDao;
    private final ContactBeanDao contactBeanDao;
    private final ETHWalletDao eTHWalletDao;
    private final IdCradBeanDao idCradBeanDao;
    private final UserInfoBeanDao userInfoBeanDao;
    private final DownInfoDao downInfoDao;
    private final CookieResulteDao cookieResulteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        btcWalletDaoConfig = daoConfigMap.get(BtcWalletDao.class).clone();
        btcWalletDaoConfig.initIdentityScope(type);

        contactBeanDaoConfig = daoConfigMap.get(ContactBeanDao.class).clone();
        contactBeanDaoConfig.initIdentityScope(type);

        eTHWalletDaoConfig = daoConfigMap.get(ETHWalletDao.class).clone();
        eTHWalletDaoConfig.initIdentityScope(type);

        idCradBeanDaoConfig = daoConfigMap.get(IdCradBeanDao.class).clone();
        idCradBeanDaoConfig.initIdentityScope(type);

        userInfoBeanDaoConfig = daoConfigMap.get(UserInfoBeanDao.class).clone();
        userInfoBeanDaoConfig.initIdentityScope(type);

        downInfoDaoConfig = daoConfigMap.get(DownInfoDao.class).clone();
        downInfoDaoConfig.initIdentityScope(type);

        cookieResulteDaoConfig = daoConfigMap.get(CookieResulteDao.class).clone();
        cookieResulteDaoConfig.initIdentityScope(type);

        btcWalletDao = new BtcWalletDao(btcWalletDaoConfig, this);
        contactBeanDao = new ContactBeanDao(contactBeanDaoConfig, this);
        eTHWalletDao = new ETHWalletDao(eTHWalletDaoConfig, this);
        idCradBeanDao = new IdCradBeanDao(idCradBeanDaoConfig, this);
        userInfoBeanDao = new UserInfoBeanDao(userInfoBeanDaoConfig, this);
        downInfoDao = new DownInfoDao(downInfoDaoConfig, this);
        cookieResulteDao = new CookieResulteDao(cookieResulteDaoConfig, this);

        registerDao(BtcWallet.class, btcWalletDao);
        registerDao(ContactBean.class, contactBeanDao);
        registerDao(ETHWallet.class, eTHWalletDao);
        registerDao(IdCradBean.class, idCradBeanDao);
        registerDao(UserInfoBean.class, userInfoBeanDao);
        registerDao(DownInfo.class, downInfoDao);
        registerDao(CookieResulte.class, cookieResulteDao);
    }
    
    public void clear() {
        btcWalletDaoConfig.clearIdentityScope();
        contactBeanDaoConfig.clearIdentityScope();
        eTHWalletDaoConfig.clearIdentityScope();
        idCradBeanDaoConfig.clearIdentityScope();
        userInfoBeanDaoConfig.clearIdentityScope();
        downInfoDaoConfig.clearIdentityScope();
        cookieResulteDaoConfig.clearIdentityScope();
    }

    public BtcWalletDao getBtcWalletDao() {
        return btcWalletDao;
    }

    public ContactBeanDao getContactBeanDao() {
        return contactBeanDao;
    }

    public ETHWalletDao getETHWalletDao() {
        return eTHWalletDao;
    }

    public IdCradBeanDao getIdCradBeanDao() {
        return idCradBeanDao;
    }

    public UserInfoBeanDao getUserInfoBeanDao() {
        return userInfoBeanDao;
    }

    public DownInfoDao getDownInfoDao() {
        return downInfoDao;
    }

    public CookieResulteDao getCookieResulteDao() {
        return cookieResulteDao;
    }

}
