package com.alsc.net.db.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ETHWALLET".
*/
public class ETHWalletDao extends AbstractDao<ETHWallet, Long> {

    public static final String TABLENAME = "ETHWALLET";

    /**
     * Properties of entity ETHWallet.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Password = new Property(2, String.class, "password", false, "PASSWORD");
        public final static Property Address = new Property(3, String.class, "address", false, "ADDRESS");
        public final static Property KeystorePath = new Property(4, String.class, "keystorePath", false, "KEYSTORE_PATH");
        public final static Property Mnemonic = new Property(5, String.class, "mnemonic", false, "MNEMONIC");
        public final static Property BtcPrivateKey = new Property(6, String.class, "btcPrivateKey", false, "BTC_PRIVATE_KEY");
        public final static Property BtcAddress = new Property(7, String.class, "btcAddress", false, "BTC_ADDRESS");
        public final static Property BtcFilePath = new Property(8, String.class, "btcFilePath", false, "BTC_FILE_PATH");
        public final static Property IsCurrent = new Property(9, boolean.class, "isCurrent", false, "IS_CURRENT");
        public final static Property IsBackup = new Property(10, boolean.class, "isBackup", false, "IS_BACKUP");
    }


    public ETHWalletDao(DaoConfig config) {
        super(config);
    }
    
    public ETHWalletDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ETHWALLET\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"PASSWORD\" TEXT," + // 2: password
                "\"ADDRESS\" TEXT," + // 3: address
                "\"KEYSTORE_PATH\" TEXT," + // 4: keystorePath
                "\"MNEMONIC\" TEXT," + // 5: mnemonic
                "\"BTC_PRIVATE_KEY\" TEXT," + // 6: btcPrivateKey
                "\"BTC_ADDRESS\" TEXT," + // 7: btcAddress
                "\"BTC_FILE_PATH\" TEXT," + // 8: btcFilePath
                "\"IS_CURRENT\" INTEGER NOT NULL ," + // 9: isCurrent
                "\"IS_BACKUP\" INTEGER NOT NULL );"); // 10: isBackup
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ETHWALLET\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ETHWallet entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(3, password);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(4, address);
        }
 
        String keystorePath = entity.getKeystorePath();
        if (keystorePath != null) {
            stmt.bindString(5, keystorePath);
        }
 
        String mnemonic = entity.getMnemonic();
        if (mnemonic != null) {
            stmt.bindString(6, mnemonic);
        }
 
        String btcPrivateKey = entity.getBtcPrivateKey();
        if (btcPrivateKey != null) {
            stmt.bindString(7, btcPrivateKey);
        }
 
        String btcAddress = entity.getBtcAddress();
        if (btcAddress != null) {
            stmt.bindString(8, btcAddress);
        }
 
        String btcFilePath = entity.getBtcFilePath();
        if (btcFilePath != null) {
            stmt.bindString(9, btcFilePath);
        }
        stmt.bindLong(10, entity.getIsCurrent() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsBackup() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ETHWallet entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(3, password);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(4, address);
        }
 
        String keystorePath = entity.getKeystorePath();
        if (keystorePath != null) {
            stmt.bindString(5, keystorePath);
        }
 
        String mnemonic = entity.getMnemonic();
        if (mnemonic != null) {
            stmt.bindString(6, mnemonic);
        }
 
        String btcPrivateKey = entity.getBtcPrivateKey();
        if (btcPrivateKey != null) {
            stmt.bindString(7, btcPrivateKey);
        }
 
        String btcAddress = entity.getBtcAddress();
        if (btcAddress != null) {
            stmt.bindString(8, btcAddress);
        }
 
        String btcFilePath = entity.getBtcFilePath();
        if (btcFilePath != null) {
            stmt.bindString(9, btcFilePath);
        }
        stmt.bindLong(10, entity.getIsCurrent() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsBackup() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ETHWallet readEntity(Cursor cursor, int offset) {
        ETHWallet entity = new ETHWallet( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // password
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // address
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // keystorePath
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // mnemonic
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // btcPrivateKey
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // btcAddress
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // btcFilePath
            cursor.getShort(offset + 9) != 0, // isCurrent
            cursor.getShort(offset + 10) != 0 // isBackup
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ETHWallet entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPassword(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAddress(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setKeystorePath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMnemonic(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBtcPrivateKey(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBtcAddress(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBtcFilePath(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setIsCurrent(cursor.getShort(offset + 9) != 0);
        entity.setIsBackup(cursor.getShort(offset + 10) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ETHWallet entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ETHWallet entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ETHWallet entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
